-- +goose Up 
CREATE TABLE IF NOT EXISTS personal_message (
  chat_id UUID PRIMARY KEY REFERENCES chat(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  is_seen  BOOLEAN NOT NULL DEFAULT FALSE,
  send_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down 
DROP TABLE IF EXISTS personal_message;
