// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Chat struct {
	ID        uuid.UUID
	Content   string
	Type      interface{}
	CreatedAt sql.NullTime
	UserID    sql.NullInt32
}

type ChatGroup struct {
	ID        uuid.UUID
	Name      string
	About     string
	Ppic      sql.NullString
	CreatedAt sql.NullTime
}

type ChatGroupMember struct {
	GroupID  uuid.UUID
	UserID   int32
	IsAdmin  sql.NullBool
	JoinedAt sql.NullTime
}

type User struct {
	ID             int32
	Username       string
	Email          string
	PasswordHashed string
	CreatedAt      sql.NullTime
}
