// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Chat struct {
	ID        uuid.UUID
	Content   string
	Type      interface{}
	CreatedAt sql.NullTime
	UserID    sql.NullInt32
}

type User struct {
	ID             int32
	Username       string
	Email          string
	PasswordHashed string
	CreatedAt      sql.NullTime
}
