// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Chat struct {
	ID        uuid.UUID
	Content   string
	Type      interface{}
	CreatedAt sql.NullTime
	UserID    sql.NullInt32
}

type ChatGroup struct {
	ID                 uuid.UUID
	Name               string
	About              string
	Ppic               sql.NullString
	CreatedAt          sql.NullTime
	RequiredPermission bool
}

type ChatGroupMember struct {
	GroupID  uuid.UUID
	UserID   int32
	IsAdmin  sql.NullBool
	JoinedAt sql.NullTime
}

type ChatGroupMessage struct {
	ChatID      uuid.UUID
	ChatGroupID uuid.UUID
	SenderID    int32
	SendAt      sql.NullTime
}

type ChatGroupQueue struct {
	UserID      int32
	ChatGroupID uuid.UUID
	IsAccepted  sql.NullBool
	RequestedAt sql.NullTime
}

type Friend struct {
	UserID    int32
	FriendID  int32
	CreatedAt sql.NullTime
}

type PersonalMessage struct {
	ChatID     uuid.UUID
	SenderID   int32
	ReceiverID int32
	IsSeen     bool
	SendAt     sql.NullTime
}

type PersonalW struct {
	ID    uuid.UUID
	Usera sql.NullInt32
	Userb sql.NullInt32
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    sql.NullInt32
	Token     string
	ExpiresAt sql.NullTime
	CreatedAt sql.NullTime
}

type User struct {
	ID             int32
	Username       string
	Email          string
	PasswordHashed string
	CreatedAt      sql.NullTime
}

type UsersInfo struct {
	UserID int32
	Pimage sql.NullString
	Pbio   sql.NullString
}
