// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (username , email , password_hashed)
VALUES ($1 , $2 , $3)
RETURNING id, username, email, password_hashed, created_at
`

type AddUserParams struct {
	Username       string
	Email          string
	PasswordHashed string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser, arg.Username, arg.Email, arg.PasswordHashed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHashed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hashed, created_at 
FROM users 
WHERE ID = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHashed,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hashed, created_at
FROM users 
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHashed,
		&i.CreatedAt,
	)
	return i, err
}

const getUserbyEmail = `-- name: GetUserbyEmail :one
SELECT id, username, email, password_hashed, created_at
FROM users 
WHERE email = $1
`

func (q *Queries) GetUserbyEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserbyEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHashed,
		&i.CreatedAt,
	)
	return i, err
}

const getUsersAll = `-- name: GetUsersAll :many
SELECT id, username, email, password_hashed, created_at
FROM users 
ORDER BY created_at desc
`

func (q *Queries) GetUsersAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHashed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPasswordByEmail = `-- name: UpdateUserPasswordByEmail :exec
UPDATE users 
  set password_hashed = $2 
WHERE email = $1
`

type UpdateUserPasswordByEmailParams struct {
	Email          string
	PasswordHashed string
}

func (q *Queries) UpdateUserPasswordByEmail(ctx context.Context, arg UpdateUserPasswordByEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordByEmail, arg.Email, arg.PasswordHashed)
	return err
}

const updateUserPasswordByUsername = `-- name: UpdateUserPasswordByUsername :exec
UPDATE users 
  set password_hashed = $2
WHERE username = $1
`

type UpdateUserPasswordByUsernameParams struct {
	Username       string
	PasswordHashed string
}

func (q *Queries) UpdateUserPasswordByUsername(ctx context.Context, arg UpdateUserPasswordByUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordByUsername, arg.Username, arg.PasswordHashed)
	return err
}

const updateUserUsernameByEmail = `-- name: UpdateUserUsernameByEmail :exec
UPDATE users 
  set username = $2
WHERE email = $1
`

type UpdateUserUsernameByEmailParams struct {
	Email    string
	Username string
}

func (q *Queries) UpdateUserUsernameByEmail(ctx context.Context, arg UpdateUserUsernameByEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserUsernameByEmail, arg.Email, arg.Username)
	return err
}
