// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users_info.sql

package db

import (
	"context"
	"database/sql"
)

const addUserInfo = `-- name: AddUserInfo :one
INSERT INTO users_info (user_id , pimage, pbio)
VALUES ($1 , $2 , $3) 
RETURNING user_id, pimage, pbio
`

type AddUserInfoParams struct {
	UserID int32
	Pimage sql.NullString
	Pbio   sql.NullString
}

func (q *Queries) AddUserInfo(ctx context.Context, arg AddUserInfoParams) (UsersInfo, error) {
	row := q.db.QueryRowContext(ctx, addUserInfo, arg.UserID, arg.Pimage, arg.Pbio)
	var i UsersInfo
	err := row.Scan(&i.UserID, &i.Pimage, &i.Pbio)
	return i, err
}

const deleteUserInfo = `-- name: DeleteUserInfo :exec
DELETE FROM users_info WHERE user_id = $1
`

func (q *Queries) DeleteUserInfo(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserInfo, userID)
	return err
}

const getUserInfo = `-- name: GetUserInfo :one
SELECT user_id, pimage, pbio FROM users_info 
WHERE user_id = $1
`

func (q *Queries) GetUserInfo(ctx context.Context, userID int32) (UsersInfo, error) {
	row := q.db.QueryRowContext(ctx, getUserInfo, userID)
	var i UsersInfo
	err := row.Scan(&i.UserID, &i.Pimage, &i.Pbio)
	return i, err
}

const updateUserInfo = `-- name: UpdateUserInfo :exec
UPDATE users_info 
  set pimage = $2,
      pbio = $3
WHERE user_id = $1
`

type UpdateUserInfoParams struct {
	UserID int32
	Pimage sql.NullString
	Pbio   sql.NullString
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfo, arg.UserID, arg.Pimage, arg.Pbio)
	return err
}

const updateUserInfoBio = `-- name: UpdateUserInfoBio :exec
UPDATE users_info 
  set pbio = $2
WHERE user_id = $1
`

type UpdateUserInfoBioParams struct {
	UserID int32
	Pbio   sql.NullString
}

func (q *Queries) UpdateUserInfoBio(ctx context.Context, arg UpdateUserInfoBioParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfoBio, arg.UserID, arg.Pbio)
	return err
}

const updateUserInfoImage = `-- name: UpdateUserInfoImage :exec
UPDATE users_info 
  set pimage = $2
WHERE user_id = $1
`

type UpdateUserInfoImageParams struct {
	UserID int32
	Pimage sql.NullString
}

func (q *Queries) UpdateUserInfoImage(ctx context.Context, arg UpdateUserInfoImageParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfoImage, arg.UserID, arg.Pimage)
	return err
}
